//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unapec.HumanResourcesM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unapec.HumanResourcesM.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicante.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNAPEC Gestor RRHH.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidato.
        /// </summary>
        public static string Candidate {
            get {
                return ResourceManager.GetString("Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han descartado todos los candidatos seleccionados..
        /// </summary>
        public static string Message_ApplicantsDiscarded {
            get {
                return ResourceManager.GetString("Message_ApplicantsDiscarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felicitaciones! Has finalizado correctamente el formulario de aplicación para nuestro puesto de trabajo. En un periodo de 2 a 3 días estarás recibiendo una respuesta a tu solicitud..
        /// </summary>
        public static string Message_ApplicationWizardConfirmation {
            get {
                return ResourceManager.GetString("Message_ApplicationWizardConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para continuar, debe completar / corregir los valores..
        /// </summary>
        public static string Message_CreationFormInvalidFields {
            get {
                return ResourceManager.GetString("Message_CreationFormInvalidFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han registrado con éxito los nuevos empleados a partir de los candidatos seleccionados..
        /// </summary>
        public static string Message_EmployeesFromApplicantsCreated {
            get {
                return ResourceManager.GetString("Message_EmployeesFromApplicantsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema ha detectado que es su primer intento de acceso al sistema. Su primera contraseña, debe ser su Número de Identificación o Cédula..
        /// </summary>
        public static string Message_FirstLogin {
            get {
                return ResourceManager.GetString("Message_FirstLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se han guardado exitosamente..
        /// </summary>
        public static string Message_FormSubmitSuccess {
            get {
                return ResourceManager.GetString("Message_FormSubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva oferta de empleo registrada correctamente..
        /// </summary>
        public static string Message_JobOfferCreated {
            get {
                return ResourceManager.GetString("Message_JobOfferCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se han registrado {0} empleados para la capacitación..
        /// </summary>
        public static string Message_QuorumSuccessWithCount {
            get {
                return ResourceManager.GetString("Message_QuorumSuccessWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales de acceso introducidas son incorrectas..
        /// </summary>
        public static string Message_WrongCredentials {
            get {
                return ResourceManager.GetString("Message_WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal / Activo.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En vacaciones.
        /// </summary>
        public static string OnVacaction {
            get {
                return ResourceManager.GetString("OnVacaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Seleccionado.
        /// </summary>
        public static string PreSelected {
            get {
                return ResourceManager.GetString("PreSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está a punto de finalizar y guardar los datos. 
        ///Está seguro que ha revisado y completado la información correctamente?.
        /// </summary>
        public static string Question_CreationFormSubmit {
            get {
                return ResourceManager.GetString("Question_CreationFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estás a punto de cerrar el proceso y guardar tus datos. 
        ///Estás seguro que has revisado y completado tu información correctamente?.
        /// </summary>
        public static string Question_WizardNewApplicationSubmit {
            get {
                return ResourceManager.GetString("Question_WizardNewApplicationSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazado.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajo Supervisión.
        /// </summary>
        public static string UnderSupervision {
            get {
                return ResourceManager.GetString("UnderSupervision", resourceCulture);
            }
        }
    }
}
